sudo: required 
dist: bionic 
language: generic
branches:
  only:
  - travis-ci

cache:
  directories:
    - $HOME/.ccache

compiler:
  - gcc
notifications:
  email:
    on_failure: always

env:
  global:
   - ROS_REPO=ros
   - NOT_TEST_INSTALL=true
   - CCACHE_DIR=$HOME/.ccache  
   - ECS_API=http://127.0.0.1:8000
   - AGENT_POST_API=https://postman-echo.com
   - ECS_DB_LOC=rosrect-ecs-api-server/ecs.db
  matrix:
    - USE_DEB=true  
      ROS_DISTRO="melodic" 
      ROS_REPO=ros
      ADDITIONAL_DEBS="libcpprest-dev curl"
      CMAKE_ARGS="-DENABLE_COVERAGE_TESTING=ON -DCMAKE_BUILD_TYPE=Debug"
      DOCKER_RUN_OPTS="--net=host"

allow_failures:
    - env: ROS_DISTRO="melodic" ROS_REPO=ros  ADDITIONAL_DEBS="libcpprest-dev"

before_install:
  #installing microsoft libcpprest dependency
  - sudo apt-get install libcpprest-dev
  - pip install --user cpp-coveralls

install:
  - git clone https://github.com/cognicept-admin/rosrect-ecs-api-server.git  
  - git clone https://github.com/ros-industrial/industrial_ci.git .industrial_ci -b master

before_script:
  - sudo apt-get update
  - sudo apt-get install python3-pip
  - sudo apt-get install python3-setuptools
  - sudo apt install gcovr
  - pip3 install sanic
  - pip3 install databases
  - pip3 install aiosqlite
  - export ECS_API=http://127.0.0.1:8000
  - export AGENT_POST_API=https://postman-echo.com
  - export ECS_DB_LOC=rosrect-ecs-api-server/ecs.db
  - chmod +x ci-test.sh
  - ./ci-test.sh
  - sleep 10

script:
  - curl 'http://127.0.0.1:8000/ping'
  - source .industrial_ci/travis.sh
  - gcovr -r . --exclude-directories test
  - curl 'http://127.0.0.1:8000/ping'


after_success:
  - coveralls --gcov-options '\-lp'

